# Copyright © 2024–2026 Faith Frontier Ecclesiastical Trust. All rights reserved.
# PROPRIETARY — See LICENSE.

name: Enforce License Headers

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: HawkEye - License Header Check
        uses: korandoru/hawkeye@v6
        with:
          config: .licenserc.toml
